### ISSUE TITLE
Primeros pasos 

### ISSUE THREAD

**Issue by MariaVictoria** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#18]
Cristian y Denisse, establecerán la estructura básica sobre la cual trabajaremos luego los html, y definirán la paleta de colores.

**Comment by bit-rec98** [comment]
Desarrollo en progreso

**Comment by bit-rec98** [comment]
La paleta de colores ya está definida, es la siguiente: 
https://coolors.co/222222-f5f5f5-2a5006-366608

**Comment by bit-rec98** [comment]
Se están trabajando las validaciones de la escritura de los archivos .html y .css en los sitios correspondientes de W3C a la vez que se realizan las pruebas con la sección del Lighthouse desde el inspector del navegador.

**Comment by bit-rec98** [comment]
Ya se realizaron las validaciones correspondientes en las páginas de W3C y se realizaron los tests en la sección Lighthouse del inspector del navegador. Queda pendiente revisar un aspecto de la performance en esta sección de lighthouse para poder mejorar el puntaje obtenido.

**Comment by bit-rec98** [comment]
> Podrían dejar por acá el diseño de figma?
> 

Hoy mismo agrego el link acá así lo documentamos

**Comment by bit-rec98** [comment]
Link al diseño en Figma: https://www.figma.com/file/Y3tsKgI4GG7jqOVNgzZbaQ/TiendaDeCampeones_wireframe?type=design&node-id=0%3A1&mode=design&t=t29G0htHOpH05bYn-1
