### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MariaVictoria** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#19]
Victoria diseñará el logo de la tienda

**Comment by MariaVictoria** [comment]
Se diseña un primer prototipo de logo , sujeto a revisión por el equipo

**Comment by bit-rec98** [comment]
El diseño del logo se aprobó así que ya está en implementación

**Comment by DenisseSabeff** [comment]
Se realizó un cambio de colores en el logo en donde se aplican los colores seleccionados de la paleta ya elegida.

**Comment by bit-rec98** [comment]
El diseño del logo ya está aprobado y puesto en práctica. Quedaba pendiente remover el fondo para que quede como un .png
