### ISSUE TITLE
Base de Datos 

### ISSUE THREAD

**Issue by MariaVictoria** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#20]
Gustavo y Abril definirán el diagrama DER para la creación de la base de datos.

**Comment by MariaVictoria** [comment]
Gastón se suma al equipo para participar en esta tarea. 
Abril abandona el equipo de trabajo

**Comment by toskamon** [comment]
base de datos finalizada.esperando carga masiva de productos y clientes para subirla al repositorio
