### ISSUE TITLE
Diagramas

### ISSUE THREAD

**Issue by MariaVictoria** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#21]
Denisse de encargará de definir el Diagrama de Clases  y casos de uso (Python) en colaboración con Gustavo . y Gastón que se suma al equipo.

**Comment by DenisseSabeff** [comment]
Diagrama de clases en proceso!

**Comment by toskamon** [comment]
DEER finalizado.falta diagrama de clases que ya se encuentra en proceso

**Comment by DenisseSabeff** [comment]
Diagrama de clases finalizado y aprobado por el grupo.

**Comment by DenisseSabeff** [comment]
Modelo Relacional Finalizado.
