### ISSUE TITLE
About

### ISSUE THREAD

**Issue by MariaVictoria** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#22]
Pablo será el encargado de la construcción de la about page.
Trabaja con Denisse en la presentación.

**Comment by pabloscr** [comment]
creando formularios en html y aplicando css en bordes

**Comment by DenisseSabeff** [comment]
Idea de Texto introductorio para la presentación, queda sujeta a revisión. 
"Bienvenidos a Tienda de Campeones: Revive la Historia del Fútbol a través de Nuestras Camisetas
En Tienda de Campeones, somos apasionados amantes del fútbol y de su historia. Nuestro viaje en el tiempo nos lleva a rescatar las camisetas de los países que han conquistado la cima del deporte más grande del mundo.
Cada camiseta es una ventana al pasado: representa el sudor y la dedicación de los jugadores que compartieron un sueño común.
Con un equipo compuesto por fanáticos del fútbol y expertos en moda deportiva, estamos comprometidos en revivir estas historias únicas.
Únete a nosotros en esta travesía de celebración y nostalgia. Explora nuestra tienda en línea para descubrir auténticas camisetas de los campeones de la Copa Mundial. Cada compra es un tributo a la historia y un recordatorio constante del espíritu de lucha y victoria.
Celebra la grandeza del fútbol. Celebra la historia. Bienvenidos a Tienda de Campeones."

**Comment by pabloscr** [comment]
Se agrego a la rama Pablo about.html, sujeto a modificar el texto y subir nuevamente a la rama Pablo, también se modifico style.css.

**Comment by pabloscr** [comment]
ya se efectuó el cambio de texto en about.html rama Pablo.
