### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by MariaVictoria** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#25]
Se designa a Lautaro para que trabaje en responsive,

**Comment by LautaroPena02** [comment]
Me encargare del responsive del index y el about, aun continúan en proceso de desarrollo.

**Comment by LautaroPena02** [comment]
Pablo me notifico que subió a su rama el archivo about.html, en el cual voy a realizar el responsive y luego actualizare.
