### ISSUE TITLE
Desarrollo de la estructura del backend

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#28]
Gustavo se encargará de realizar la estructura modular del código escrito en Python al igual que el código correspondiente para el CRUD y los servicios del sistema de la página.

**Comment by toskamon** [comment]
En desarrollo

**Comment by toskamon** [comment]
se creo la carpeta backend con las entidades y la clase conexion

**Comment by toskamon** [comment]
se comienza a trabajar en los servicios de cada clase

**Comment by toskamon** [comment]
se finalizo el servicio producto
