### ISSUE TITLE
Asignación de tareas para Sprint 2 - FrontEnd

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#59]
- Estructuración de formulario de login: Pablo
- Estructuración de formulario de registro: Vicky

- Escritura de código JS para procesamiento de datos del formulario de login: Lautaro y Cristian
- Escritura de código JS para procesamiento de datos del formulario de registro: Denisse y Cristian
- Escritura de código JS para modificaciones de interfaz: Cristian

**Comment by MariaVictoria** [comment]
Actualicé  registro de usuario

**Comment by LautaroPena02** [comment]
Finalizo parte del código de JS para procesamiento de datos del formulario de login.
