### ISSUE TITLE
Asignación de tareas adicionales

### ISSUE THREAD

**Issue by bit-rec98** [Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023#63]
Tareas a realizar por Denisse: 
Realización de la descripción de los casos de uso
Rediseño del footer para aplicarlo a todas las páginas .html 
Realización de validaciones de formulario de contacto
Realización de validaciones de formulario de registro de usuarios

**Comment by DenisseSabeff** [comment]
En proceso el rediseño del footer!
Terminado y aprobado por el grupo el archivo de descripcion de casos de uso.

**Comment by DenisseSabeff** [comment]
Aprobado el diseño del footer. Listo para subir

**Comment by DenisseSabeff** [comment]
Código subido, aprobado por el grupo y en funcionamiento de footer, validaciones de formulario de Contacto y validaciones para el registro de usuario.
